config/routes.rb
Rails.application.routes.draw do
  resources :backlogs
	root 'briefs#index', as: 'briefs_index'
    resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backlog.rb
class Backlog < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :description, :image_url, presence: true 
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  before_action :set_backlog, only: [:show, :edit, :update, :destroy]

  # GET /backlogs
  # GET /backlogs.json
  def index
    @backlogs = Backlog.all
  end

  # GET /backlogs/1
  # GET /backlogs/1.json
  def show
  end

  # GET /backlogs/new
  def new
    @backlog = Backlog.new
  end

  # GET /backlogs/1/edit
  def edit
  end

  # POST /backlogs
  # POST /backlogs.json
  def create
    @backlog = Backlog.new(backlog_params)

    respond_to do |format|
      if @backlog.save
        format.html { redirect_to @backlog, notice: 'Backlog was successfully created.' }
        format.json { render :show, status: :created, location: @backlog }
      else
        format.html { render :new }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlogs/1
  # PATCH/PUT /backlogs/1.json
  def update
    respond_to do |format|
      if @backlog.update(backlog_params)
        format.html { redirect_to @backlog, notice: 'Backlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @backlog }
      else
        format.html { render :edit }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backlogs/1
  # DELETE /backlogs/1.json
  def destroy
    @backlog.destroy
    respond_to do |format|
      format.html { redirect_to backlogs_url, notice: 'Backlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog
      @backlog = Backlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_params
      params.fetch(:backlog, {})
    end
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  def index
  	@posts = Post.order(:title)
  end
end

app/controllers/concerns/current_backlog.rb
module CurrentBacklog

	private

	  def set_backlog
	  	@backlog = Backlog.find(session[:cart_id])
	  rescue ActiveRecord::RecordNotFound
	  	@backlog = Backlog.create
	  	session[:cart_id] = @cart.cart_id
	  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/backlogs/_form.html.erb
<%= form_with(model: backlog, local: true) do |form| %>
  <% if backlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(backlog.errors.count, "error") %> prohibited this backlog from being saved:</h2>

      <ul>
      <% backlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/backlogs/edit.html.erb
<h1>Editing Backlog</h1>

<%= render 'form', backlog: @backlog %>

<%= link_to 'Show', @backlog %> |
<%= link_to 'Back', backlogs_path %>

app/views/backlogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Backlogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backlogs.each do |backlog| %>
      <tr>
        <td><%= link_to 'Show', backlog %></td>
        <td><%= link_to 'Edit', edit_backlog_path(backlog) %></td>
        <td><%= link_to 'Destroy', backlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backlog', new_backlog_path %>

app/views/backlogs/new.html.erb
<h1>New Backlog</h1>

<%= render 'form', backlog: @backlog %>

<%= link_to 'Back', backlogs_path %>

app/views/backlogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_backlog_path(@backlog) %> |
<%= link_to 'Back', backlogs_path %>

app/views/briefs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Your Pragmatic Catalog</h1>

<% @posts.each do |post| %> 
  <div class="entry">
    <%= image_tag(post.image_url) %> 
    <h3><%= post.title %></h3>
    <%= sanitize(post.description) %> 
    <div class="price_line">
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GhostScribe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name%>'>
    <div id="banner">

      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <ul>
          <li><a href="http://www.......">Home</a></li>
          <li><a href="http://www.......">Faq</a></li>
          <li><a href="http://www.......">News</a></li>
          <li><a href="http://www.......">Contact</a></li>
        </ul>
      </div>
      <div id="main">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :post_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p> <h1>Posts</h1>
  <table>
   <% @posts.each do |post| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
     <td>
     <%= image_tag(post.image_url, class: 'list_image') %> </td>
     <td class="list_description"> 
       <dl>
        <dt><%= post.title %> 
        </dt>
          <dd><%= truncate(strip_tags(post.description),
          length: 80) %>
          </dd>
        </dl> 
      </td>
      <td class="list_actions">
      <%= link_to 'Show', post %>

     <br/>

    <%= link_to 'Edit', edit_post_path(post) %><br/>

    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
     </td> 
   </tr>
  <% end %>
  </table>
 <br />

<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> title:</strong>
  <%= @post. title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @post.image_url %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>